services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
      REDIS_HOST: redis  
      REDIS_PORT: 6379    
      NODE_ENV: production
    depends_on:
      - db
      - redis

volumes:
  postgres_data: