# Usa una imagen base oficial de Node.js
FROM node:16-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar archivos de la aplicación
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código de la aplicación
COPY . .

# Exponer el puerto en el que correrá la aplicación
EXPOSE 3000

# Definir el comando para iniciar la aplicación
CMD ["npm", "start"]
